# Generated by Django 5.1.1 on 2024-09-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employer_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(unique=True)),
                ("hash", models.TextField()),
                ("firstname", models.TextField()),
                ("lastname", models.TextField()),
                ("is_candidate", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("email", models.TextField()),
                ("phone", models.TextField()),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobBangApiapp.employer_info",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employer_info",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="JobBangApiapp.user",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="candidate_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobBangApiapp.user",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
