# Generated by Django 5.1.1 on 2024-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JobBangApiapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate_info",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employer_info",
            name="company_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
