# Generated by Django 5.1.1 on 2024-09-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBangApiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_info',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate_info',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobBangApiapp.user', to_field='_id', unique=True),
        ),
        migrations.AlterField(
            model_name='employer_info',
            name='company_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employer_info',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobBangApiapp.user', to_field='_id', unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JobBangApiapp.employer_info', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='error',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(null=True),
        ),
    ]
